name: Bug Reports
description: File a bug report
title: "[Bug]: "
labels: ["bug", "triage"]
assignees:
  - octocat
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: markdown
    attributes:
      value: | 
         # बैंकिंग संबंध + उत्पाद / चैनल
    validations: 
      required: true
  - type: input
    id: Bank
    attributes:
      label: बैंक खाता
      description: बैंक बचत खातों / डाकघर खातों की संख्या
      placeholder: उदाहरण - संख्या
    validations:
      required: true
  - type: input
    id: Bank-detail
    attributes:
      label: बैंक का नाम
      description: बैंकों / शाखा का नाम
      placeholder: उदाहरण - भारतीय स्टेट बैंक
    validations:
      required: true
  - type: markdown
    attributes:
      value: | 
         ##  बैंकिंग उत्पाद/सेवाएं
    validations: 
      required: true
  - type: dropdown
    id: Check-book
    attributes:
      label: चेक बुक
      description: क्या आपके पास चेक बुक है?
      multiple: true
      options:
        - "हाँ"
        - "नहीं"
        - चुप रहना पसंद करूंगा
        - मैं नहीं कहना चाहता
    validations:
      required: true
  - type: dropdown
    id: ATM-Debit
    attributes:
      label: एटीएम/डेबिट कार्ड
      description: क्या आपके पास एटीएम/डेबिट कार्ड है?
      multiple: true
      options:
        - "हाँ"
        - "नहीं"
        - चुप रहना पसंद करूंगा
        - मैं नहीं कहना चाहता
    validations:
      required: true
  - type: dropdown
    id: Credit-Card
    attributes:
      label: क्रेडिट कार्ड
      description: क्या आपके पास क्रेडिट कार्ड है?
      multiple: true
      options:
        - "हाँ"
        - "नहीं"
        - चुप रहना पसंद करूंगा
        - मैं नहीं कहना चाहता
    validations:
      required: true
  - type: dropdown
    id: Loans
    attributes:
      label: ऋण
      description: क्या आपने सोना, किसान आदि कोई कर्ज लिया है?
      multiple: true
      options:
        - "हाँ"
        - "नहीं"
        - चुप रहना पसंद करूंगा
        - मैं नहीं कहना चाहता
    validations:
      required: true
  - type: input
    id: branch
    attributes:
      label: शाखा के माध्यम से उत्पाद
      description: नाम
    validations:
      required: true
  - type: input
    id: Business
    attributes:
      label: व्यवसाय संवाददाता / बैंक मित्र, डाकघर के माध्यम से उत्पाद
      description: नाम
    validations:
      required: true
  - type: dropdown
    id: Internet-Banking
    attributes:
      label: ऑनलाइन / मोबाइल बैंकिंग
      description: क्या आप इंटरनेट बैंकिंग का उपयोग कर रहे हैं?
      multiple: true
      options:
        - "हाँ"
        - "नहीं"
        - चुप रहना पसंद करूंगा
        - मैं नहीं कहना चाहता
    validations:
      required: true
  - type: textarea
    id: Others
    attributes:
      label: अन्य 
      description: नाम
    validations:
      required: true  
    - type: markdown
    attributes:
      value: | 
         # Payments and Transfers (Monthly / Annual)
    validations: 
      required: true
  - type: textarea
    id: upi
    attributes:
      label: UPI or UPI enabled apps
      description: You are using any UPI apps?
      placeholder:  BHIM
    validations:
      required: true
  - type: input
    id: wallets
    attributes:
      label: Used Wallets
      description: You are using wallets?
      placeholder:  Yes / No
    validations:
      required: true
  - type: input
    id: counts
    attributes:
      label: 	Typical Count of Local Payments per month (in proximity / phone number, UPI-handle etc.)
      description: Number of counts
      placeholder:  Number
    validations:
      required: true
  - type: input
    id: Local-payment
    attributes:
      label: Typical amount for Local payments
      description: Approx amount using through UPI
      placeholder:  "10,000"
    validations:
      required: true
  - type: input
    id: QR
    attributes:
      label: QR Code based Payments
      description: Are you making payment through QR code?
      placeholder:  Yes / No
    validations:
      required: true
  - type: input
    id: rent
    attributes:
      label: Rent
      description: You have your own house / you are living in Rent
      placeholder:  Yes / No
    validations:
      required: true
  - type: dropdown
    id: Transport
    attributes:
      label: Local Transport
      description: Which type of local transport you are using?
      multiple: true
      options:
        - Metro
        - Train
        - Bus
        - Others
    validations:
      required: true
  - type: markdown
    attributes:
      value: | 
         ## Other BBPS list:
    validations: 
      required: true
  - type: input
    id: recharge
    attributes:
      label: Phone / data Recharge
      description: Are you using UPI for recharge payments?
      placeholder:  Yes / No
    validations:
      required: true
  - type: input
    id: Electricity
    attributes:
      label: Electricity / Water / Utilities
      description: Are you using UPI for Electricity / Water bills payments?
      placeholder:  Yes / No
    validations:
      required: true
  - type: input
    id: othe
    attributes:
      label: Others
      description: Are you using UPI for other payments?
      placeholder:  Yes / No
    validations:
      required: true
  - type: dropdown
    id: remote
    attributes:
      label: Remote payments / fund transfers
      description: Are you using UPI payments for remote payments?
      multiple: true
      options:
        - Wallet
        - UPI
        - NEFT/IMPS/RTGS
        - Other Method
    validations:
      required: true
