name: Bug Reports
description: File a bug report
title: "[Bug]: "
labels: ["bug", "triage"]
assignees:
  - octocat
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: markdown
    attributes:
      value: | 
         # बैंकिंग संबंध + उत्पाद / चैनल
    validations: 
      required: true
  - type: input
    id: Bank
    attributes:
      label: बैंक खाता
      description: बैंक बचत खातों / डाकघर खातों की संख्या
      placeholder: उदाहरण - संख्या
    validations:
      required: true
  - type: input
    id: Bank-detail
    attributes:
      label: बैंक का नाम
      description: बैंकों / शाखा का नाम
      placeholder: उदाहरण - भारतीय स्टेट बैंक
    validations:
      required: true
  - type: markdown
    attributes:
      value: | 
         ##  बैंकिंग उत्पाद/सेवाएं
    validations: 
      required: true
  - type: dropdown
    id: Check-book
    attributes:
      label: चेक बुक
      description: क्या आपके पास चेक बुक है?
      multiple: true
      options:
        - "हाँ"
        - "नहीं"
        - चुप रहना पसंद करूंगा
        - मैं नहीं कहना चाहता
    validations:
      required: true
  - type: dropdown
    id: ATM-Debit
    attributes:
      label: एटीएम/डेबिट कार्ड
      description: क्या आपके पास एटीएम/डेबिट कार्ड है?
      multiple: true
      options:
        - "हाँ"
        - "नहीं"
        - चुप रहना पसंद करूंगा
        - मैं नहीं कहना चाहता
    validations:
      required: true
  - type: dropdown
    id: Credit-Card
    attributes:
      label: क्रेडिट कार्ड
      description: क्या आपके पास क्रेडिट कार्ड है?
      multiple: true
      options:
        - "हाँ"
        - "नहीं"
        - चुप रहना पसंद करूंगा
        - मैं नहीं कहना चाहता
    validations:
      required: true
  - type: dropdown
    id: Loans
    attributes:
      label: ऋण
      description: क्या आपने सोना, किसान आदि कोई कर्ज लिया है?
      multiple: true
      options:
        - "हाँ"
        - "नहीं"
        - चुप रहना पसंद करूंगा
        - मैं नहीं कहना चाहता
    validations:
      required: true
  - type: input
    id: branch
    attributes:
      label: शाखा के माध्यम से उत्पाद
      description: नाम
    validations:
      required: true
  - type: input
    id: Business
    attributes:
      label: व्यवसाय संवाददाता / बैंक मित्र, डाकघर के माध्यम से उत्पाद
      description: नाम
    validations:
      required: true
  - type: dropdown
    id: Internet-Banking
    attributes:
      label: ऑनलाइन / मोबाइल बैंकिंग
      description: क्या आप इंटरनेट बैंकिंग का उपयोग कर रहे हैं?
      multiple: true
      options:
        - "हाँ"
        - "नहीं"
        - चुप रहना पसंद करूंगा
        - मैं नहीं कहना चाहता
    validations:
      required: true
  - type: textarea
    id: Others
    attributes:
      label: अन्य 
      description: नाम
    validations:
      required: true  
