name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug", "triage"]
assignees:
  - octocat
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: markdown
    attributes:
      value: | 
         # Banking relationship + Products / Channels
    validations: 
      required: true
  - type: input
    id: Bank
    attributes:
      label: Bank Account
      description: How many bank accounts do you have.
      placeholder: Number
    validations:
      required: true
  - type: input
    id: Post
    attributes:
      label: Post Office Account
      description: How many Post office accounts do you have.
      placeholder: Number
    validations:
      required: true    
  - type: input
    id: Bank-detail
    attributes:
      label: Name of Bank
      description: Name of Banks/branch.
      placeholder: SBI
    validations:
      required: true
  - type: dropdown
    id: Banking-product
    attributes:
      label: Banking Products
      description: What are the banking services you use
      multiple: true
      options:
        - Cheque Book
        - ATM / Debit Card
        - Credit Card
        - Net Banking
        - Loans
        - Insurance
    validations:
      required: true    
  - type: input
    id: gov-scheme
    attributes:
      label: Government Schemes
      description: What are the government benefit Schemes you use 
      placeholder: Atal Pension Yojana/Samrudhi Youjana/Others
    validations:
      required: true 
  - type: input
    id: branch
    attributes:
      label: Products via branch
      description: Services/Items which we used
      placeholder: Cheque book/ATM/Credit Cards
    validations:
      required: true
  - type: input
    id: Business
    attributes:
      label: Products via Business correspondent / Bank Mitra, Post office 
      description: Name
    validations:
      required: true
  - type: dropdown
    id: Internet-Banking
    attributes:
      label: Online / Mobile banking.
      description: Are you using Internet banking
     # multiple: true
      options:
        - "Yes"
        - "No"
        - Prefer not to say
        - I do not say
    validations:
      required: true
  - type: input
    id: Others
    attributes:
      label: Others 
      description: Name
    validations:
      required: true  
  - type: dropdown
    id: remote-family
    attributes:
      label: Remote Family
      description: Do you transfer money to remote family?
      # multiple: true
      options:
        - "Yes"
        - "No"
        - Do not know
        - will not say
    validations:
      required: true
  - type: input
    id: Remote-family-money
    attributes:
      label: Remote Family Money
      description: How much money do you transfer to remote family in a month?
      placeholder: Number
    validations:
      required: true
  - type: input
    id: financial-notes
    attributes:
      label: Financial Notes
      description: Amount of money sent to someone other than family.
      placeholder: "6,000"
    validations:
      required: true
  - type: markdown
    attributes:
      value: "## Investments"

  - type: input
    id: prompt5a
    attributes:
      label: FD / RD		
      placeholder: Enter the amount in INR
    validations:
      required: true
  - type: input
    id: prompt5b
    attributes:
      label: Mutual Funds 				
      placeholder: Enter the amount in INR
    validations:
      required: true
  - type: input
    id: prompt5c
    attributes:
      label: Others				
      placeholder: Enter the amount in INR
    validations:
      required: true  
  - type: input
    id: prompt5d
    attributes:
      label: Others				
      placeholder: Enter the amount in INR
    validations:
     # required: true
  - type: markdown
    attributes:
      value: "## Loans / Liability "

  - type: input
    id: prompt6a
    attributes:
      label: Loan Type					
      placeholder: Write here
    validations:
      required: true

  - type: input
    id: prompt6b
    attributes:
      label: Amount			 				
      placeholder: Enter the amount in INR
    validations:
      required: true

  - type: input
    id: prompt6c
    attributes:
      label: Bank			 				
      placeholder: Write here
    validations:
      required: true

  - type: input
    id: prompt6d
    attributes:
      label: Loan Type					
      placeholder: Write here
    validations:
      #required: true

  - type: input
    id: prompt6e
    attributes:
      label: Amount			 				
      placeholder: Enter the amount in INR
    validations:
     # required: true

  - type: input
    id: prompt6f
    attributes:
      label: Bank			 				
      placeholder: Write here
    validations:
     # required: true
    
  - type: markdown
    attributes:
      value: | 
         # Payments and Transfers (Monthly / Annual)
    validations: 
      required: true
  - type: dropdown
    id: upi
    attributes:
      label: UPI-enabled apps
      description: Do you have any app/s related to UPI?
      options:
        - "Yes"
        - "No"
        - Do not know
        - will not say
    validations:
      required: true
  - type: input
    id: upi-apps
    attributes:
      label: Number of UPI apps
      description: How many such apps you have installed in your mobile?
      placeholder: Number
    validations:
      required: true
  - type: input
    id: upi-app-detail
    attributes:
      label: UPI apps detail
      description: UPI or UPI enabled app/s details 
      placeholder: BHIM/Phonepe/G-pay/Paytem
    validations:
      required: true
  - type: dropdown
    id: wallets
    attributes:
      label: Used Wallets
      description: Have you ever used Wallets during transaction?
      options:
        - "Yes"
        - "No"
        - Do not know
        - will not say
    validations:
      required: true
  - type: input
    id: wallet-weekly
    attributes:
      label: Wallet Weekly
      description: How often do you use Wallet for any transaction weekly?
      placeholder: "1,000"
    validations:
      required: true
  - type: input
    id: counts
    attributes:
      label: 	Local Payment Counts
      description: How often do you use UPI handles/phone numbers for Local Payment/s in a month? 
      placeholder:  Number
    validations:
      required: true
  - type: input
    id: Local-payment
    attributes:
      label: Local Payment Amount
      description: How much have you spent/transfer last month in Local payments
      placeholder:  "10,000"
    validations:
      required: true
  - type: dropdown
    id: QR
    attributes:
      label: QR Code based Payments
      description: Have you used QR code/s as a payment option/s?
      options:
        - "Yes"
        - "No"
        - Do not know
        - will not say
    validations:
      required: true
  - type: input
    id: qr-counts
    attributes:
      label: 	QR Payment Counts
      description: How often you use QR code for payments? 
      placeholder:  Number
    validations:
      required: true
  - type: input
    id: QR-weekly
    attributes:
      label: QR Payment Weekly
      description: QR Code based payments in last week
      placeholder: "2,000"
    validations:
      required: true  
  - type: input
    id: QR-amount
    attributes:
      label: QR Payment Amount
      description: 	QR Code based payment (on an average per month)
      placeholder:  "8,000"
    validations:
      required: true     
  - type: dropdown
    id: Transport
    attributes:
      label: UPI Payment for Local Transport
      description: Do you use UPI payment methods for local transportation purposes (such as metro/bus/MRTS/Ola/Uber)
      # multiple: true
      options:
        - "Yes"
        - "No"
        - Do not know
        - will not say
    validations:
      required: true
  - type: input
    id: Local-payment-transport
    attributes:
      label: Local Transportation Amount
      description: How much usually do you spend on transportation using UPI payment methods?
      placeholder:  "10,000"
    validations:
      required: true
  - type: dropdown
    id: BBPS
    attributes:
      label: BBPS Facilities
      description: Do you use UPI-based payment methods in other BBPS facilities (Select all that apply)
      multiple: true
      options:
        - Phone/Data recharge
        - Electricity
        - Water bills
        - Utility bills
        - Online Purchase
        - Others
    validations:
      required: true
  - type: dropdown
    id: remote
    attributes:
      label: Remote payments / fund transfers
      description: Are you using UPI payments for remote payments?
      multiple: true
      options:
        - Wallet
        - UPI
        - NEFT/IMPS/RTGS
        - Other Method
    validations:
      required: true
